# Generated by Django 6.1.1 on 2026-10-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_wishlist_unique_wishlist_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Placed', max_length=50),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
